version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

      # Install jq to parse JSON from Secrets Manager
      - yum install -y jq

      # Fetch GitHub token from Secrets Manager (replace with your actual secret ID)
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id my-github-token --query SecretString --output text | jq -r '.token')

  build:
    commands:
      - echo "Starting build..."
      - python main.py
      - mkdir -p output
      - echo "This is a demo artifact" > output/artifact.txt

  post_build:
    commands:
      - echo "Build completed on `date`"

      # Clone the same GitHub repo into a temp folder
      - git clone https://${GITHUB_TOKEN}@github.com/NitishCuddapah/BuildArtifact.git temp-repo
      - cd temp-repo

      # Set Git identity for commit
      - git config user.name "NitishCuddapah"
      - git config user.email "nitishcuddapah.7@gmail.com"

      - git checkout main
      - mkdir -p build-artifacts

      # Copy and commit the artifact
      - cp ../output/artifact.txt build-artifacts/
      - git add build-artifacts/
      - git commit -m "Add new artifact - $(date)" || echo "Nothing to commit"
      - echo "GITHUB_TOKEN=$GITHUB_TOKEN"
      - git push https://${GITHUB_TOKEN}@github.com/NitishCuddapah/BuildArtifact.git HEAD:main

artifacts:
  files:
    - '**/*'
