version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting build..."
      - python main.py
      - mkdir -p output
      - echo "This is a demo artifact" > output/artifact.txt

  post_build:
    commands:
      - echo "Build completed on `date`"

      - git clone https://${GITHUB_TOKEN}@github.com/NitishCuddapah/BuildArtifact.git temp-repo
      - cd temp-repo

      - git config user.name "NitishCuddapah"
      - git config user.email "nitishcuddapah.7@gmail.com"

      - git checkout main
      - mkdir -p build-artifacts

      - cp ../output/artifact.txt build-artifacts/
      - git add build-artifacts/
      - git commit -m "Add new artifact - $(date)" || echo "Nothing to commit"
      - git push origin HEAD:main

artifacts:
  files:
    - '**/*'
