version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting build..."
      - python main.py
      - echo "Simulating JAR output"
      - mkdir -p output
      - echo "This is a demo artifact" > output/output.jar 

  post_build:
    commands:
      - echo "Build completed on `date`"

      # Cloning the same GitHub repo into a temp folder
      - git clone https://${github_token}@github.com/NitishCuddapah/BuildArtifact.git temp-repo
      - cd temp-repo

      - git config user.name "NitishCuddapah"
      - git config user.email "nitishcuddapah.7@gmail.com"

      - git checkout main
      - mkdir -p build-artifacts

      # Copy output artifact from CodeBuild workspace to repo
      - cp ../output/output.jar build-artifacts/

      # Commit and push the new artifact
      - git add build-artifacts/
      - git commit -m "Add new artifact - $(date)"
      - git remote set-url origin https://${github_token}@github.com/NitishCuddapah/BuildArtifact.git
      - git push https://${github_token}@github.com/NitishCuddapah/BuildArtifact.git HEAD:main


artifacts:
  files:
    - '**/*'
