version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Starting build..."
      - python main.py
  post_build:
    commands:
      - echo "Build finished on `date`"
      - git init
      - git config user.name "NitishCuddapah"
      - git config user.email "nitishcuddapah.7@gmail.com"
      - git branch -M main
      - git add .
      - git commit -m "Upload build artifact from codebuild"
      - git push -u origin main
artifacts:
  files:
    - output/**/*
